// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TibberVictronController.Web.Data;

#nullable disable

namespace TibberVictronController.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318165317_InitialCreate4")]
    partial class InitialCreate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("TibberVictronController.Web.Models.DecisionHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetPowerWatts")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("DecisionHistory");
                });

            modelBuilder.Entity("TibberVictronController.Web.Models.EnergyStateHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BatteryPowerWatts")
                        .HasColumnType("REAL");

                    b.Property<double>("BatterySocPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("GridPowerWatts")
                        .HasColumnType("REAL");

                    b.Property<double>("HouseConsumptionWatts")
                        .HasColumnType("REAL");

                    b.Property<double>("PvPowerWatts")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("EnergyStateHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
